import { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { SoftSkyBackdrop } from '@/components/backgrounds/SoftSkyBackdrop';
import { setWaiverAccepted } from '@/modules/crowdfunding/utils/waiverState';

export default function CrowdfundingWaiver() {
  const [accepted, setAccepted] = useState(false);

  const handleAccept = () => {
    setWaiverAccepted(true);
    router.replace('/crowdfunding');
  };

  return (
    <SoftSkyBackdrop>
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => router.back()}
            activeOpacity={0.7}
          >
            <Ionicons name="arrow-back" size={24} color="#1F2937" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Legal Agreement</Text>
          <View style={{ width: 40 }} />
        </View>

        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.contentContainer}
          showsVerticalScrollIndicator={true}
        >
          <View style={styles.heroCard}>
            <View style={styles.iconCircle}>
              <Ionicons name="shield-checkmark" size={40} color="#EF4444" />
            </View>
            <Text style={styles.heroTitle}>Important Legal Notice</Text>
            <Text style={styles.heroSubtitle}>
              Please read and accept the following terms before accessing litigation funding
              opportunities
            </Text>
          </View>

          <View style={styles.contentCard}>
            <Text style={styles.mainTitle}>
              Legali's Fund Your Litigation (Crowdfunding & Investing in Litigation) Waiver —
              Platform Terms
            </Text>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>1.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>Platform Purpose and Limitation</Text>
                <Text style={styles.sectionText}>
                  Legali operates as a technology platform facilitating litigation crowdfunding.
                  Legali does not provide investment advice, financial recommendations, legal
                  opinions, or endorsements for any specific funding opportunity. All information is
                  provided for informational purposes only. Users—funders, applicants, lawyers,
                  investors, donors—must make their own independent assessments and decisions.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>2.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>No Investment Recommendation Disclaimer</Text>
                <Text style={styles.sectionText}>
                  Legali and its affiliates do not offer, recommend, or endorse any investment
                  opportunities, specific case assessments, or expectations regarding returns.
                  {'\n\n'}
                  Nothing on this platform constitutes legal, investment, or financial advice.
                  Platform users are not clients or customers of Legali for investment advisory or
                  legal services.
                  {'\n\n'}
                  Each user is responsible for independent due diligence and should consult external
                  financial, legal, or other professional advisors before any decision to
                  participate.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>3.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>AI Risk Assessment Disclosure</Text>
                <View style={styles.warningBadge}>
                  <Ionicons name="warning" size={16} color="#F59E0B" />
                  <Text style={styles.warningText}>AI-Generated Content</Text>
                </View>
                <Text style={styles.sectionText}>
                  All preliminary analytics, risk estimates, or case assessments are generated by
                  AI-powered tools. These outputs are non-binding, informational, and do not
                  represent the advice or opinions of Legali or its staff.
                  {'\n\n'}
                  Final funding decisions require review by a licensed, independent lawyer and
                  submission and verification of supporting documentation before any funds are
                  distributed.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>4.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>Regulatory and Funding Disclosures</Text>
                <Text style={styles.sectionText}>
                  Participation in crowdfunding through Legali may implicate federal and state
                  securities law and regulatory compliance. Legali is not a registered
                  broker-dealer, funding portal, or investment advisor, and does not intermediate,
                  warrant, or guarantee any transaction.
                  {'\n\n'}
                  Users are responsible for their own compliance, must heed all risk and eligibility
                  disclosures, and must acknowledge required regulatory notices.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>5.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>Risk and Security Notice</Text>
                <View style={styles.dangerBadge}>
                  <Ionicons name="alert-circle" size={16} color="#EF4444" />
                  <Text style={styles.dangerText}>High Risk Investment</Text>
                </View>
                <Text style={styles.sectionText}>
                  Litigation outcomes are unpredictable and all investments are inherently risky. AI
                  assessments, legal review, or platform safeguards do not guarantee any result.
                  Investors may lose all or part of their contributions.
                  {'\n\n'}
                  Users agree to assume these risks and waive claims against Legali for losses,
                  adverse outcomes, or reliance on platform information.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>6.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>Documentation and Legal Review</Text>
                <Text style={styles.sectionText}>
                  Applicants must provide accurate, complete documentation for independent legal
                  review. Failure to provide required documents or disclosures results in forfeiture
                  of funding eligibility.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>7.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>Privacy and Communications</Text>
                <Text style={styles.sectionText}>
                  Users accept that litigation crowdfunding may require limited public disclosure of
                  case information, subject to privacy laws and privilege. No confidential advice or
                  privileged communications will be shared via Legali.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>8.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>Informed Consent</Text>
                <Text style={styles.sectionText}>
                  By using this platform, users acknowledge and agree:
                  {'\n\n'}• They have read and understood these terms;
                  {'\n'}• They are not receiving investment, legal, or financial advice from Legali;
                  and
                  {'\n'}• They accept all legal, regulatory, and financial risks resulting from
                  participating in litigation crowdfunding activity.
                </Text>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionNumber}>9.</Text>
              <View style={styles.sectionContent}>
                <Text style={styles.sectionTitle}>
                  Reporting Suspicious Campaigns and Activities
                </Text>
                <Text style={styles.sectionText}>
                  All users—including lawyers, investors, clients, and donors—are empowered and
                  encouraged to report any campaign or transaction that appears suspicious,
                  fraudulent, or raises concerns regarding legitimacy, compliance, or investor
                  protection.
                </Text>
              </View>
            </View>

            <View style={styles.dividerSection}>
              <View style={styles.dividerLine} />
            </View>

            <View style={styles.additionalSection}>
              <Text style={styles.sectionText}>
                Legali maintains accessible reporting channels on the platform for users to submit
                concerns. All verified reports are promptly investigated and, where necessary,
                escalated to authorities or regulatory bodies in accordance with law.
              </Text>
            </View>

            <View style={styles.additionalSection}>
              <Text style={styles.sectionText}>
                Legali reserves the right to freeze, remove, or suspend any campaign if fraud,
                abuse, or illicit activity is suspected.
              </Text>
            </View>
          </View>
        </ScrollView>

        <View style={styles.footer}>
          <TouchableOpacity
            style={styles.checkboxRow}
            onPress={() => setAccepted(!accepted)}
            activeOpacity={0.7}
          >
            <View style={[styles.checkbox, accepted && styles.checkboxActive]}>
              {accepted && <Ionicons name="checkmark" size={18} color="#FFFFFF" />}
            </View>
            <Text style={styles.checkboxText}>
              I have read and agree to all terms and conditions above
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.acceptButton, !accepted && styles.acceptButtonDisabled]}
            onPress={handleAccept}
            activeOpacity={0.8}
            disabled={!accepted}
          >
            <Text style={styles.acceptButtonText}>Accept & Continue</Text>
            <Ionicons name="arrow-forward" size={20} color="#FFFFFF" />
          </TouchableOpacity>
        </View>
      </View>
    </SoftSkyBackdrop>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FEF2F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 8,
    textAlign: 'center',
  },
  heroSubtitle: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
  },
  contentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  mainTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 24,
    lineHeight: 24,
  },
  section: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  sectionNumber: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2937',
    marginRight: 8,
    minWidth: 20,
  },
  sectionContent: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 8,
  },
  sectionText: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 22,
  },
  warningBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFBEB',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  warningText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#F59E0B',
  },
  dangerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FEF2F2',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  dangerText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#EF4444',
  },
  dividerSection: {
    marginVertical: 24,
  },
  dividerLine: {
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  additionalSection: {
    marginBottom: 16,
    paddingLeft: 0,
  },
  footer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 16,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxActive: {
    backgroundColor: '#2B8CAF',
    borderColor: '#2B8CAF',
  },
  checkboxText: {
    flex: 1,
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 20,
    fontWeight: '600',
  },
  acceptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#2B8CAF',
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: '#2B8CAF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  acceptButtonDisabled: {
    backgroundColor: '#D1D5DB',
    shadowOpacity: 0,
  },
  acceptButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
